/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as DiscussionsIndexRouteImport } from './routes/discussions.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as VideosNewRouteImport } from './routes/videos.new'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as DiscussionsNewRouteImport } from './routes/discussions.new'
import { Route as DiscussionsPostIdRouteImport } from './routes/discussions.$postId'
import { Route as CoursesNewRouteImport } from './routes/courses.new'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as CoursesCourseIdEditRouteImport } from './routes/courses.$courseId.edit'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsIndexRoute = DiscussionsIndexRouteImport.update({
  id: '/discussions/',
  path: '/discussions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosNewRoute = VideosNewRouteImport.update({
  id: '/videos/new',
  path: '/videos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsNewRoute = DiscussionsNewRouteImport.update({
  id: '/discussions/new',
  path: '/discussions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsPostIdRoute = DiscussionsPostIdRouteImport.update({
  id: '/discussions/$postId',
  path: '/discussions/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdEditRoute = CoursesCourseIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/setup': typeof AdminSetupRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/new': typeof CoursesNewRoute
  '/discussions/$postId': typeof DiscussionsPostIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/u/$userId': typeof UUserIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/videos/new': typeof VideosNewRoute
  '/courses/': typeof CoursesIndexRoute
  '/discussions/': typeof DiscussionsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/setup': typeof AdminSetupRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/new': typeof CoursesNewRoute
  '/discussions/$postId': typeof DiscussionsPostIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/u/$userId': typeof UUserIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/videos/new': typeof VideosNewRoute
  '/courses': typeof CoursesIndexRoute
  '/discussions': typeof DiscussionsIndexRoute
  '/videos': typeof VideosIndexRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/setup': typeof AdminSetupRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/new': typeof CoursesNewRoute
  '/discussions/$postId': typeof DiscussionsPostIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/u/$userId': typeof UUserIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/videos/new': typeof VideosNewRoute
  '/courses/': typeof CoursesIndexRoute
  '/discussions/': typeof DiscussionsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/admin/setup'
    | '/courses/$courseId'
    | '/courses/new'
    | '/discussions/$postId'
    | '/discussions/new'
    | '/u/$userId'
    | '/videos/$videoId'
    | '/videos/new'
    | '/courses/'
    | '/discussions/'
    | '/videos/'
    | '/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/admin/setup'
    | '/courses/$courseId'
    | '/courses/new'
    | '/discussions/$postId'
    | '/discussions/new'
    | '/u/$userId'
    | '/videos/$videoId'
    | '/videos/new'
    | '/courses'
    | '/discussions'
    | '/videos'
    | '/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/admin/setup'
    | '/courses/$courseId'
    | '/courses/new'
    | '/discussions/$postId'
    | '/discussions/new'
    | '/u/$userId'
    | '/videos/$videoId'
    | '/videos/new'
    | '/courses/'
    | '/discussions/'
    | '/videos/'
    | '/courses/$courseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  AdminSetupRoute: typeof AdminSetupRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  CoursesNewRoute: typeof CoursesNewRoute
  DiscussionsPostIdRoute: typeof DiscussionsPostIdRoute
  DiscussionsNewRoute: typeof DiscussionsNewRoute
  UUserIdRoute: typeof UUserIdRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  VideosNewRoute: typeof VideosNewRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DiscussionsIndexRoute: typeof DiscussionsIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/': {
      id: '/discussions/'
      path: '/discussions'
      fullPath: '/discussions/'
      preLoaderRoute: typeof DiscussionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/new': {
      id: '/videos/new'
      path: '/videos/new'
      fullPath: '/videos/new'
      preLoaderRoute: typeof VideosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/new': {
      id: '/discussions/new'
      path: '/discussions/new'
      fullPath: '/discussions/new'
      preLoaderRoute: typeof DiscussionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/$postId': {
      id: '/discussions/$postId'
      path: '/discussions/$postId'
      fullPath: '/discussions/$postId'
      preLoaderRoute: typeof DiscussionsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/edit': {
      id: '/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof CoursesCourseIdEditRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdEditRoute: typeof CoursesCourseIdEditRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdEditRoute: CoursesCourseIdEditRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  AdminSetupRoute: AdminSetupRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  CoursesNewRoute: CoursesNewRoute,
  DiscussionsPostIdRoute: DiscussionsPostIdRoute,
  DiscussionsNewRoute: DiscussionsNewRoute,
  UUserIdRoute: UUserIdRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  VideosNewRoute: VideosNewRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DiscussionsIndexRoute: DiscussionsIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
