/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscussionsNewRouteImport } from './routes/discussions.new'
import { Route as DiscussionsPostIdRouteImport } from './routes/discussions.$postId'
import { Route as CoursesNewRouteImport } from './routes/courses.new'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CoursesCourseIdEditRouteImport } from './routes/courses.$courseId.edit'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsNewRoute = DiscussionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DiscussionsRoute,
} as any)
const DiscussionsPostIdRoute = DiscussionsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => DiscussionsRoute,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdEditRoute = CoursesCourseIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/videos': typeof VideosRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/new': typeof CoursesNewRoute
  '/discussions/$postId': typeof DiscussionsPostIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/videos': typeof VideosRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/new': typeof CoursesNewRoute
  '/discussions/$postId': typeof DiscussionsPostIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/videos': typeof VideosRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/new': typeof CoursesNewRoute
  '/discussions/$postId': typeof DiscussionsPostIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/discussions'
    | '/videos'
    | '/courses/$courseId'
    | '/courses/new'
    | '/discussions/$postId'
    | '/discussions/new'
    | '/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/discussions'
    | '/videos'
    | '/courses/$courseId'
    | '/courses/new'
    | '/discussions/$postId'
    | '/discussions/new'
    | '/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/courses'
    | '/discussions'
    | '/videos'
    | '/courses/$courseId'
    | '/courses/new'
    | '/discussions/$postId'
    | '/discussions/new'
    | '/courses/$courseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DiscussionsRoute: typeof DiscussionsRouteWithChildren
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/new': {
      id: '/discussions/new'
      path: '/new'
      fullPath: '/discussions/new'
      preLoaderRoute: typeof DiscussionsNewRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/discussions/$postId': {
      id: '/discussions/$postId'
      path: '/$postId'
      fullPath: '/discussions/$postId'
      preLoaderRoute: typeof DiscussionsPostIdRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId/edit': {
      id: '/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof CoursesCourseIdEditRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdEditRoute: typeof CoursesCourseIdEditRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdEditRoute: CoursesCourseIdEditRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  CoursesNewRoute: typeof CoursesNewRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  CoursesNewRoute: CoursesNewRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DiscussionsRouteChildren {
  DiscussionsPostIdRoute: typeof DiscussionsPostIdRoute
  DiscussionsNewRoute: typeof DiscussionsNewRoute
}

const DiscussionsRouteChildren: DiscussionsRouteChildren = {
  DiscussionsPostIdRoute: DiscussionsPostIdRoute,
  DiscussionsNewRoute: DiscussionsNewRoute,
}

const DiscussionsRouteWithChildren = DiscussionsRoute._addFileChildren(
  DiscussionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DiscussionsRoute: DiscussionsRouteWithChildren,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
